# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace = "boringcache/gluten"

[proxy]
metadata-hints = [
  "project=apache-gluten",
  "issue=12743",
  "workload=velox-native-library",
  "input=16d9ceab541608eb45f858d3cb09c0245252e1acca89f6a25723702aea07c936",
]

[entries.velox-native]
tag = "velox-native-d3b0ef63fcf212bfa9c5b35f68e8cbad63e65f29669a3f8373df2f7ca99a6376"
path = "cpp/build"
no-git = true

[profiles.velox-native]
entries = ["velox-native"]
